language: ruby
rvm:
- 1.9.3
env:
- CHEF_VERSION=10.24.0
- CHEF_VERSION=10.26.0
- CHEF_VERSION=10.28.0
- CHEF_VERSION=11.4.0
- CHEF_VERSION=11.4.4
- CHEF_VERSION=11.6.0
before_script:
- chef-client --version
notifications:
  hipchat:
    rooms:
      secure: MHwgEIb1oXDENsYBLehgNHZ5OvXrdEXzDJY16ciYDriEiauUS6cxaPUBJknVd7kOFLB+HU8ADhVqxVEK7K+Ob0P/31YrBeNz/ujct/Y9ldWFcJ4XqAUZPryW4ZZEhfOnnE2j8ZQhtVpHev1/xdyVCEG13uB9VMPhvPLMeQuikAU=
